### ISSUE TITLE
Charge assignment with AM1BCC results in non-zero charge

### ISSUE THREAD

**Issue by rmatsum836** [rsdefever/antefoyer#13]
I've been attempting to use antefoyer to apply am1bcc charges to several simple small molecules.  Methane, water, and butane result in total non-zero charges on the order of 1E-3.  

To check that this wasn't an issue with rounding, I ran antechamber from the command line and viewed the outputs of several file formats, including MOL2 and AC.  Upon inspecting the files, the charges don't appear to be rounded.

A minimum working example can be viewed here:
https://gist.github.com/rmatsum836/7a6b8e96b73d5adb621a4c4112b1b5a5

**Comment by rmatsum836** [comment]
One option mentioned is to redistribute the charge over the atoms.  I think this would be somewhat arbitrary but I think it would also be good to have a tolerance, where the charge assignment would fail if the non-zero charge is greater than the tolerance.

**Comment by rsdefever** [comment]
I would favor a `tol` option that will rescale to the desired charge, unless the net charge differs by more than `tol.` I would think a reasonable default value for `tol` would be on the order of `0.01`.
